function About() {
    return (
        <section className="description">
            <h2>About</h2>
            {/* text generated by ChatGPT - https://openai.com/blog/chatgpt/ */}
            <p>Hi there! My name is Mittens and I'm a feline professional with years of experience in napping, birdwatching, and expert cuddling. As a domestic long-haired cat, I pride myself on being a versatile and adaptable companion for humans.</p>
        </section>
    );
}

export default About;