function Interests() {
    return (
        <section className="description">
            <h2>Interests</h2>
            {/* text generated by ChatGPT - https://openai.com/blog/chatgpt/ */}
            <p>In my spare time, I enjoy sharpening my claws on a variety of scratching posts, playing with my favorite toys, and grooming my luxurious coat. I'm a firm believer in the power of self-care and always make time for a good grooming session.</p>
        </section>
    );
}

export default Interests;